sudo: required
dist: trusty
addons:
  apt:
    packages:
    - nodejs
    - npm
services:
- docker
language: java
jdk:
- oraclejdk8
install:
- bash .travis/update.sh
- export M2_HOME=/usr/share/maven3 && export PATH=${M2_HOME}/bin:${PATH} && export MAVEN_OPTS="-Xms2048m -Xmx2048m"
- java -version && javac -version && mvn -version -B
- npm install -g dockerfile_lint
before_script:
- mvn dependency:resolve-plugins dependency:resolve -B
- docker pull docker.io/centos/python-27-centos7:latest
- dockerfile_lint -f base/Dockerfile -r .travis/dockerlint_rule.yaml
- dockerfile_lint -f rule1/Dockerfile -r .travis/dockerlint_rule.yaml
script:
- mvn clean install -B -Dgpg.skip=true
- docker build --tag garethahealy/elastoplast-base:latest base
- docker build --tag garethahealy/elastoplast-rule1:latest rule1
cache:
  directories:
  - $HOME/.m2
  - $HOME/.victims
