sudo: required
dist: trusty
addons:
  apt:
    sources:
    - debian-sid
    packages:
    - nodejs
    - npm
services:
- docker
language: java
jdk:
- oraclejdk8
install:
- bash .travis/update.sh
- export M2_HOME=/usr/share/maven3 && export PATH=${M2_HOME}/bin:${PATH} && export MAVEN_OPTS="-Xms2048m -Xmx2048m"
- java -version && javac -version && mvn -version -B
before_script:
- mvn dependency:resolve-plugins dependency:resolve -B
- docker build --tag garethahealy/elastoplast-base:latest base
- docker build --tag garethahealy/elastoplast-rule1:latest rule1
script:
- mvn clean install -B -Dgpg.skip=true
cache:
  directories:
  - $HOME/.m2
  - $HOME/.victims
